version: "1.0"
description: "Provider configuration for ChatGPT vs Copilot evaluation"

providers:
  chatgpt:
    type: "chatgpt"
    model: "gpt-4"
    temperature: 0
    max_tokens: 1200
    seed: 42
    response_format: "json_object"
    timeout_seconds: 60
    capabilities:
      web_access: false        # Default for offline tasks
      tools_allowed: false     # No additional tools
      json_required: true      # Require JSON response format
      max_retries: 3

  copilot_manual:
    type: "copilot_manual"
    display_format: "rich"      # Use rich formatting for display
    timeout: 300               # Manual response timeout (5 minutes)
    capabilities:
      web_access: false        # No web access for offline tasks
      tools_allowed: false     # No additional tools
      json_required: true      # Require JSON response format
      max_retries: 1
