version: "1.0"
description: "Default evaluation matrix for ChatGPT vs Copilot comparison"

matrix:
  - provider: "chatgpt_manual"
    test_set: "offline"
    repetitions: 1          # For stability analysis
    parallel: false         # Manual input required

  - provider: "copilot_manual"
    test_set: "offline"
    repetitions: 1          # For stability analysis
    parallel: false         # Manual input required

  - provider: "chatgpt_manual"
    test_set: "online"      # Optional deep research task
    repetitions: 1          # Single run for online tasks
    parallel: false

  - provider: "copilot_manual"
    test_set: "online"      # Optional deep research task
    repetitions: 1          # Single run for online tasks
    parallel: false

test_sets:
  offline:
    - "tests/offline/task1_metrics.yaml"
    - "tests/offline/task2_ssn_regex.yaml"
    - "tests/offline/task3_exec_summary.yaml"

  online:
    - "tests/online/deep_research_agentic_ai.yaml"

global_settings:
  output_dir: "results"
  save_raw_responses: true
  save_parsed_responses: true
  generate_report: true
  fail_fast: false         # Continue on individual test failures
