# Test execution matrix configuration
# TODO: Implement in Stage 3 - Schema & Configuration Foundation

# Execution matrix: provider × test set combinations
matrix:
  # ChatGPT offline tests (3 repetitions for stability)
  - provider: chatgpt
    test_set: offline
    repetitions: 3
    tests:
      - tests/offline/task1_metrics.yaml
      - tests/offline/task2_ssn_regex.yaml
      - tests/offline/task3_exec_summary.yaml

  # Copilot offline tests (3 repetitions for stability)
  - provider: copilot
    test_set: offline
    repetitions: 3
    tests:
      - tests/offline/task1_metrics.yaml
      - tests/offline/task2_ssn_regex.yaml
      - tests/offline/task3_exec_summary.yaml

  # Optional: Online tests (single repetition)
  - provider: chatgpt
    test_set: online
    repetitions: 1
    tests:
      - tests/online/deep_research_agentic_ai.yaml

  - provider: copilot
    test_set: online
    repetitions: 1
    tests:
      - tests/online/deep_research_agentic_ai.yaml

# Global settings
settings:
  parallel_execution: false    # Run tests sequentially for now
  continue_on_error: true     # Continue matrix if individual test fails
  save_raw_responses: true    # Store raw provider responses
  generate_report: true       # Auto-generate report after completion
