# Default scoring weights for evaluation tasks
# TODO: Implement in Stage 3 - Schema & Configuration Foundation

version: "1.0"
total_points: 105

tasks:
  task1_metrics:
    total: 40
    precision: 6      # Precision metric accuracy
    recall: 6         # Recall metric accuracy
    f1: 6            # F1 score accuracy
    accuracy: 6       # Overall accuracy metric
    confusion_matrix: # Confusion matrix components (12 points total)
      tp: 3          # True positives
      fp: 3          # False positives
      fn: 3          # False negatives
      tn: 3          # True negatives

  task2_ssn_regex:
    total: 30
    regex_validity: 18  # Regex format and constraint validation
    line_matches: 12    # Correct line matching (1 point per line)

  task3_exec_summary:
    total: 20
    structure: 12       # Title, word count, bullets, schema (3 each)
    tone: 8            # Heuristics and clarity assessment

  deep_research:        # Optional online task
    total: 10
    plan_quality: 5     # Structure and sequencing
    source_quality: 5   # Recency and verification

stability_bonus:
  enabled: true
  max_points: 5
  consistency_threshold: 0.95  # 95% consistency for full bonus
